version: "3"
services:
  event_registration_api:
    build:
      context: ./
    volumes:
      - .:/src
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    environment:
      - DB_URI=${DB_URI}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
