name: Deploy Event Registration System
on: 
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy-Event-Registration-Deployer
    runs-on: ubuntu-latest
    steps:
    - name: deploying to event registration server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: cd Event_Registration_Back/ && git pull && git pull && docker compose down && docker compose up -d
