name: remote ssh command
on: 
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Event-Registration-Deployer
    runs-on: ubuntu-latest
    steps:
    - name: deploying to event registration server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: echo 'This is a test deployment'
